name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install pnpm
        run: |
          curl -fsSL https://get.pnpm.io/install.sh | sh -
          echo "$HOME/.local/share/pnpm" >> $GITHUB_PATH
          export PATH="$HOME/.local/share/pnpm:$PATH"
          pnpm --version

      - name: Install cloudflared
        run: |
          curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o cloudflared
          chmod +x cloudflared
          sudo mv cloudflared /usr/local/bin

      - name: SSH into server and deploy (via Cloudflare Access)
        run: |
          ssh -o StrictHostKeyChecking=no \
              -o ProxyCommand="cloudflared access ssh \
                --hostname ${{ secrets.CLOUDFLARE_HOSTNAME }} \
                --id ${{ secrets.CLOUDFLARE_SERVICE_TOKEN_ID }} \
                --secret ${{ secrets.CLOUDFLARE_SERVICE_TOKEN_SECRET }} \
                --destination 127.0.0.1:22" \
              root@${{ secrets.CLOUDFLARE_HOSTNAME }} <<'EOF'
            cd /home/dokkiitech/product/okusuri
            git pull origin main
            pnpm install
            pnpm build
            pm2 restart okusuri
          EOF
