name: Deploy via Cloudflare Tunnel + SSH Key

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install pnpm
        run: |
          curl -fsSL https://get.pnpm.io/install.sh | sh -
          echo "$HOME/.local/share/pnpm" >> $GITHUB_PATH
          export PATH="$HOME/.local/share/pnpm:$PATH"
          pnpm --version

      - name: Install cloudflared
        run: |
          curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o cloudflared
          chmod +x cloudflared
          sudo mv cloudflared /usr/local/bin

      - name: Start cloudflared tunnel
        run: |
          nohup cloudflared access ssh \
            --hostname ${{ secrets.CLOUDFLARE_HOSTNAME }} \
            --destination 127.0.0.1:22 > tunnel.log 2>&1 &
          sleep 5

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p 22 127.0.0.1 >> ~/.ssh/known_hosts || true

      - name: SSH into server and deploy
        run: |
          ssh -p 22 root@127.0.0.1 <<'EOF'
            cd /home/dokkiitech/product/okusuri
            git pull origin main
            pnpm install
            pnpm build
            pm2 restart okusuri
          EOF
